name: Validate

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request: ~
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - main
      - develop

  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/prepare

      - name: Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint:check

      - name: Typecheck
        run: pnpm run types:check

      - name: Test
        run: pnpm run test

      - name: Install playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Build app
        run: pnpm run build
        env:
          PUBLIC_MAPLIBRE_TILES_API_KEY: ${{ secrets.PUBLIC_MAPLIBRE_TILES_API_KEY }}
          PUBLIC_GOOGLE_SITE_VERIFICATION_ID: ${{ secrets.PUBLIC_GOOGLE_SITE_VERIFICATION_ID }}

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # the name to save the compressed asset as
          name: pages-build
          # the directory or file to upload. adapt to your needs
          path: dist
          # the artifact is only needed for the duration of the build-deploy workflow
          # adapt to your needs
          # https://github.com/actions/upload-artifact#retention-period
          # retention-days: 1

      - name: Run e2e tests
        run: pnpm run test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  # deploy:
  #   if: ${{ github.event_name == 'push' && github.base_ref == 'main' }}
  #   needs: [validate]
  #   uses: ./.github/workflows/build-deploy.yml
